#!groovy

// Generated by IBM TransformationAdvisor
// Mon Mar 04 18:03:46 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}